stages:
  - package-release
publish:
  stage: package-release
  tags:
    - runner-two
  only:
    - staging
  environment:
    name: staging
  artifacts:
    when: always
    expire_in: 15 days
  cache:
    policy: pull
    untracked: true
    key: $CI_COMMIT_REF_SLUG
      files:
        - yarn.lock
    paths:
      - .yarn
      - node_modules
      - 'packages/*/node_modules'
  before_script:
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
    - yarn install
  script:
    - yarn publish:build
    - npx semantic-release