image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  tags: 
    - runner-one
  only: 
    - staging
  environment: 
    name: staging
  script:
    - echo "//code.bonuz.team/api/v4/projects/18/packages/npm/:_authToken=${NPM_TOKEN}">.npmrc
    # This following command is based on the information on yarnPath' key value on .yarnrc.yml
    - yarn set version 3.2.0
    - yarn -v
    # The following is set to run deployment in dry-run mode until the pipelines config complete and usable
    - npm publish --dry-run