image: node:latest
stages:
  - package-release
publish:
  stage: package-release
  tags:
    - runner-one
  only:
    - staging
  environment:
    name: staging
  artifacts:
    when: always
    expire_in: 15 days
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
    key:
      files:
        - package-lock.json
        - yarn.lock
    paths:
      - .npm/
      - node_modules/
      - build/
  before_script:
    ## Prep project registry and authentication
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
    - cat .npmrc
    ## instal dependencies
    - yarn install
  script:
    - yarn publish:build
    - npx semantic-release