nodeLinker: node-modules

npmScopes:
  bonuz:
    npmPublishRegistry: "https://code.bonuz.team/api/v4/projects/18/packages/npm/"
    npmRegistryServer: "https://code.bonuz.team/api/v4/projects/18/packages/npm/"
    
npmRegistries:
  //code.bonuz.team/api/v4/projects/18/packages/npm/:
    npmAlwaysAuth: true
    #npmAuthToken: "${GITLAB_AUTH_TOKEN:-}"
    ## Refactoring CI/CD pipelines. Added by Martin ##
    npmAuthToken: "${NPM_TOKEN}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
